### ISSUE TITLE
peerDeps out of date

### ISSUE THREAD

**Issue by dantman** [melanieseltzer/react-use-caret-position#38]
The peerDependencies are out of date. The current package requires a peer dep of React 16. Trying to install with React 17 and the latest npm will fail.

**Comment by melanieseltzer** [comment]
Thanks for the report 👍 Feel free to submit a PR, otherwise I can push a fix when I have some free time next 🙂

**Comment by melanieseltzer** [comment]
@dantman This is fixed in `1.0.3` 🙂 Please let me know if you still have any issues installing.
